// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9gFuEcSpQXCW1MeCWBAJqo2rgR1oCIpQ',
    appId: '1:444519999956:web:000fd2f071adb98bb14e41',
    messagingSenderId: '444519999956',
    projectId: 'satbrak-41e84',
    authDomain: 'satbrak-41e84.firebaseapp.com',
    storageBucket: 'satbrak-41e84.appspot.com',
    measurementId: 'G-V3LCK1JZWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsuguDX6DRS3fBUW81-u1xispPSSAPEyY',
    appId: '1:444519999956:android:df519ed274d6b781b14e41',
    messagingSenderId: '444519999956',
    projectId: 'satbrak-41e84',
    storageBucket: 'satbrak-41e84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAFNKj4IMtknIjdq7u7ImdVS3HIWGrk4Y',
    appId: '1:444519999956:ios:611ae51b7fb8f437b14e41',
    messagingSenderId: '444519999956',
    projectId: 'satbrak-41e84',
    storageBucket: 'satbrak-41e84.appspot.com',
    iosBundleId: 'com.example.amazon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAFNKj4IMtknIjdq7u7ImdVS3HIWGrk4Y',
    appId: '1:444519999956:ios:611ae51b7fb8f437b14e41',
    messagingSenderId: '444519999956',
    projectId: 'satbrak-41e84',
    storageBucket: 'satbrak-41e84.appspot.com',
    iosBundleId: 'com.example.amazon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9gFuEcSpQXCW1MeCWBAJqo2rgR1oCIpQ',
    appId: '1:444519999956:web:7519f60a8451ce3db14e41',
    messagingSenderId: '444519999956',
    projectId: 'satbrak-41e84',
    authDomain: 'satbrak-41e84.firebaseapp.com',
    storageBucket: 'satbrak-41e84.appspot.com',
    measurementId: 'G-ZKZFX1MLNN',
  );
}
